### ISSUE TITLE
 Please base it on the header-only version of ASIO that doesn't rely on Boost.

### ISSUE THREAD

**Issue by pengxu7** [liancheng/amy#1]
Can you switch header-only ASIO that doesn't rely on Boost?

**Comment by liancheng** [comment]
Thanks for the suggestion! Let me have a try.

**Comment by liancheng** [comment]
Experimenting this in [a new branch](https://github.com/liancheng/amy/tree/non-boost-asio). Already switched to the non-boost version of Asio. But still need more work if we want to:

- Remove all other (header-only) Boost dependencies (Boost.Optional, Boost.Any, etc.)
- Make Boost an optional dependency so that users may choose between Boost.Asio or just Asio.
