### ISSUE TITLE
Build this in Windows with Visual Studio 2019

### ISSUE THREAD

**Issue by ThiagoAlexsander** [liancheng/amy#21]
Any chance that this will work?
I already tried to build it after converting to VS19 with CMake, but no success.

**Comment by liancheng** [comment]
Hey @SelfLeaker, unfortunately, I don't have access to a Windows box or VS19, so not able to work on this. What errors did you hit, though?

On the other hand, since Amy is a header-only library, you don't really need to build it in order to use it. However, since I've never tested it on Windows, there are chances that it doesn't work out of the box.
